name: Deploy React App to EC2

on:
  push:
    branches:
      - main  # Run this action on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js and dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies and build
        run: |
          npm install
          CI=false npm run build

      - name: Copy files via SSH
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          # Write SSH private key to file
          echo "$SSH_KEY" > private_key.pem
          chmod 600 private_key.pem

          # Copy build files to EC2 instance
          ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST "sudo mkdir -p /var/www/html && sudo chown -R $EC2_USER:$EC2_USER /var/www/html && sudo chmod -R 755 /var/www/html"
          scp -o StrictHostKeyChecking=no -i private_key.pem -r build/* $EC2_USER@$EC2_HOST:/var/www/html

      - name: Clean up
        run: rm private_key.pem
