name: Deploy React App to EC2

on:
  push:
    branches:
      - main  # Run this action on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and dependencies
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - run: |
          npm install
          CI=false npm run build
          
      - name: Copy files via SSH
        env:
          SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}

        run: |
          echo "$SSH_KEY" > private_key.pem
          chmod 600 private_key.pem

          # Copy build files to EC2 instance
          scp -o StrictHostKeyChecking=no -i private_key.pem -r build/* $EC2_USER@$EC2_HOST:/var/www/html

      - name: Clean up
        run: rm private_key.pem
